import type { Metadata } from "next";
import { Inter, Sora } from "next/font/google";
import "@/styles/globals.css";

import { Blur } from "@/components/Blur";
import { Header } from "@/components/Header";

const inter = Inter({ subsets: ["latin"], variable: "--font-default" });

const sora = Sora({ subsets: ["latin"], variable: "--font-title" });

export const metadata: Metadata = {
  title: "apita+",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${sora.variable} font-inter bg-background outline-none`}
      >
        <Header />

        {children}

        <Blur />
      </body>
    </html>
  );
}
